type classes implementation
scala-russian/fpspeedrun pull request #6
Opened 2018-06-14 22:31 UTC by eniqen

2018-06-15 15:55 UTC, eniqen commented on src/main/scala/fpspeedrun/week_1/Ord.scala
> +        x.lengthCompare(y.size) match {
@Odomontois
длину в конце видимо глупо проверять это либо EQ уже либо длинну надо было проверить выше и типо что больше то и победило, какие вообще требования в этом деле ?

2018-06-19 08:11 UTC, Odomontois requested changes

2018-06-19 08:11 UTC, Odomontois commented on src/main/scala/fpspeedrun/lesson_1/Ratio.scala
> +  implicit val sumSemi: SemiGroup[Ratio] = (x: Ratio, y: Ratio) => sum(x, y)
несмотря на то, что это согласуется с политикой, выбранной котами, я немного против подобных дефолтных инстансов, руководствуясь питонячьим
In the face of ambiguity, refuse the temptation to guess.

2018-06-19 08:11 UTC, Odomontois commented on src/main/scala/fpspeedrun/lesson_1/Ratio.scala
> +  implicit val ratioProdMonoid: Monoid[Prod[Ratio]] = new Monoid[Prod[Ratio]] {
если определяешь моноид -  инстанс полугруппы можно выбрасывать, он просто никогда не будет юзаться

2018-06-19 08:11 UTC, Odomontois commented on src/main/scala/fpspeedrun/syntax/monoid.scala
> +    def empty[T](y: T)(implicit m: Monoid[T]): T =  m.empty
совершенно непонятный метод
`x.empty(y)`, возвращающий гарантированно нечто, не зависящее ни от х, ни от y

2018-06-19 08:11 UTC, Odomontois commented on src/main/scala/fpspeedrun/lesson_1/Ratio.scala
>  case object Ratio {
зачем case?

2018-06-19 08:11 UTC, Odomontois commented on src/main/scala/fpspeedrun/lesson_1/Ratio.scala
> +  def sum(x: Ratio,y: Ratio): Ratio = new Ratio(
либо `case class` либо `new` и `private` конструктор

2018-06-19 08:11 UTC, Odomontois commented on src/main/scala/fpspeedrun/lesson_1/Ratio.scala
> +    override def empty: Prod[Ratio] =  Prod(Ratio.empty)
Удовлетворяет ли такой empty твоим законам?

2020-08-12 15:35 UTC, closed without merging